spring:
  application:
    name: auth_service
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
    hikari:
      auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

application:
  security:
    jwt:
      secret-key: db3c9e170b50381505ae34d438745f897ccb3ad5cbfcc1608eaba3fee5cc5d20
      expiration: 300000
    refresh-token:
      expiration: 3000000
logging:
  level:
    root: DEBUG

